---
services:
  tekxitpi:
    container_name: tekxitpi
    image: ghcr.io/hafometh88/mc-tekxitpi-docker:latest
    environment:
      - VER=latest
      - MEM=4G
    ports:
      - 25565:25565
    volumes:
      - "./minecraft:/minecraft/tekxit"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "25565"]
      interval: 30s
      timeout: 10s
      retries: 3
